     
      var chart = echarts.init(document.getElementById('fill2'));

      var option = {
          tooltip: {
              textStyle:{
                  fontSize:30
              }
          },
          series: [ {
              type: 'wordCloud',
              gridSize: 2,
              sizeRange: [14, 50],
              rotationRange: [-90, 90],
              shape:'circle',
              width: 650,
              height: 450, 
              drawOutOfBound: false,
              textStyle: {
                  normal: {
                      color: function () {
                          return 'rgb(' + [
                              Math.round(Math.random() * 200),
                              Math.round(Math.random() * 279),
                              Math.round(Math.random() * 200)
                          ].join(',') + ')';
                      },
                  },
                  emphasis: {
                      shadowBlur: 10,
                      shadowColor: '#333'
                  }
              },
              //数据自己加
              data: [
              {name:'武汉',value:2729,},
              {name:'口罩',value:1655,},
              {name:'封城',value:1238,},
              {name:'疫情',value:538,},
              {name:'病毒',value:460,},
              {name:'感染',value:330,},
              {name:'加油',value:266,},
              {name:'医院',value:263,},
              {name:'希望',value:246,},
              {name:'传播',value:219,},
              {name:'肺炎',value:213,},
              {name:'隔离',value:204,},
              {name:'确诊',value:203,},
              {name:'超市',value:200,},
              {name:'问题',value:199,},
              {name:'物资',value:195,},
              {name:'全国',value:193,},
              {name:'中国',value:192,},
              {name:'黄冈',value:181,},
              {name:'生活',value:180,},
              {name:'政府',value:179,},
              {name:'国家',value:170,},
              {name:'在家',value:170,},
              {name:'病例',value:162,},
              {name:'新闻',value:160,},
              {name:'城市',value:158,},
              {name:'飞沫',value:154,},
              {name:'消息',value:150,},
              {name:'湖北',value:139,},
              {name:'医疗',value:135,},
              {name:'新型',value:135,},
              {name:'传染',value:133,},
              {name:'防护',value:133,},
              {name:'冠状病毒',value:131,},
              {name:'黄冈市',value:125,},
              {name:'回家',value:124,},
              {name:'人民',value:123,},
              {name:'时间',value:123,},
              {name:'医生',value:122,},
              {name:'封城后',value:121,},
              {name:'患者',value:120,},
              {name:'医护人员',value:118,},
              {name:'保护',value:116,},
              {name:'市长',value:113,},
              {name:'春节',value:113,},
              {name:'工作',value:111,},
              {name:'恐慌',value:111,},
              {name:'过年',value:110,},
              {name:'武汉市',value:108,},
              {name:'家人',value:107,},
              {name:'一起',value:103,},
              {name:'接触',value:95,},
              {name:'特别',value:94,},
              {name:'防止',value:94,},
              {name:'病人',value:93,},
              {name:'一线',value:91,},
              {name:'新冠',value:90,},
              {name:'医用',value:87,},
              {name:'市民',value:87,},
              {name:'严重',value:87,},
              {name:'小区',value:86,},
              {name:'重要',value:81,},
              {name:'回来',value:80,},
              {name:'专家',value:80,},
              {name:'信息',value:79,},
              {name:'感染者',value:79,},
              {name:'西方',value:75,},
              {name:'美国',value:74,},
              {name:'N95',value:74,},
              {name:'爆发',value:73,},
              {name:'控制',value:71,},
              {name:'咳嗽',value:71,},
              {name:'药店',value:69,},
              {name:'社区',value:67,},
              {name:'症状',value:67,},
              {name:'mask',value:1523,},
              {name:'Wuhan',value:1225,},
              {name:'lockdown',value:1035,},
              {name:'epidemic',value:638,},
              {name:'virus',value:423,},
              {name:'coronavirus',value:245,},
              {name:'home',value:219,},
              {name:'hospital',value:204,},
              {name:'hope',value:172,},
              {name:'spread',value:164,},
              {name:'city',value:155,},
              {name:'isolation',value:151,},
              {name:'terrible',value:102,},
              {name:'problem',value:87,},
              {name:'life',value:73,},
              {name:'things',value:73,},
              {name:'government',value:72,},
              {name:'national',value:55,},
              {name:'die',value:43,},
              {name:'novel',value:42,},
              {name:'outside',value:31,},
              {name:'dead',value:25,},
              {name:'mist',value:22,},
              ],
          } ]
      };

      chart.setOption(option);

      window.onresize = chart.resize;
